---
- hosts: localhost
  tasks:
  - name: Create a dir for storing rendered configs locally
    file: path=localconfig state=directory owner=cumulus

- hosts: 'leaf*'
  any_errors_fatal: true
  gather_facts: false
  vars_files:
    - properties.yml
  tasks:

  - name: Get my node ID
    set_fact:
      my_node_id: "{{ inventory_hostname.split('f')[1]|int }}"
    tags:
      - compute
      - always
 
  - group_by: key='leaf'
    when: "{{ 'leaf' in inventory_hostname }}"

  - name: Get loopback IP for leaves
    set_fact:
       my_ip: "{{ lo_ip_subnet|ipsubnet(32, (my_node_id|int))|ipaddr('address') }}"

  - name: Get my ASN for leaves
    set_fact:
      my_asn: "{{ bgp_leaf_asn_base|int + my_node_id|int }}"
    tags:
      - compute
      - routing


- hosts: 'spine*'
  any_errors_fatal: true
  vars_files:
    - properties.yml
  tasks:

  - name: Get my node ID
    set_fact:
      my_node_id: "{{ inventory_hostname.split('e')[1]|int }}"
    tags:
      - compute
      - always

  - group_by: key='spine'
    when: "{{ 'spine' in inventory_hostname }}"

  - name: Get loopback IP for spines
    set_fact:
       my_ip: "{{ lo_ip_subnet|ipsubnet(32, -(my_node_id|int)-1)|ipaddr('address') }}"

  - name: Get my ASN for spines
    set_fact:
      my_asn: "{{ bgp_spine_asn }}"
    tags:
      - compute
      - routing

- hosts: '!server*'
  vars_files:
    - properties.yml
  any_errors_fatal: true
  gather_facts: true
  tasks:

  - group_by: key='routers'
    when: "{{ 'spine' in inventory_hostname or 'leaf' in inventory_hostname }}"
    
  #- include: ntp.yml

   #Assume my_ip is set(new or taken from existing iface) when assignip returns

  - include: compute-leaf-vars.yml

  - include: conf-net.yml

- hosts: 'server*'
  vars_files:
    - properties.yml
  tasks:
    - include: hostset.yml

  handlers:
    - name: Reboot server to bring up bonds
      command: /usr/bin/systemd-run --on-active=10 /bin/systemctl reboot
      async: 0
      poll: 0
      tags:
        - command
        - hosts
        - ifconfig
